name:                sudoku-engine
version:             0.1.0.0
github:              "mrdimosthenis/sudoku-engine"
license:             WTFPL
author:              "Dimosthenis Michailidis"
maintainer:          "mrdimosthenis@hotmail.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mrdimosthenis/sudoku-engine#readme>

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

executables:
  sudoku-engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku-engine

tests:
  sudoku-engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sudoku-engine
    - hspec
